# Generated by Django 4.2.1 on 2023-05-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_user_fpi_alter_user_phone_alter_user_threshold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=254)),
                ('entrytimestamp', models.CharField(max_length=30)),
                ('car_number', models.CharField(max_length=10)),
            ],
        ),
    ]
