# Generated by Django 4.2.1 on 2023-05-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_floors_username_alter_parkingentry_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dynamicpricing',
            field=models.BooleanField(default=False),
        ),
    ]
