# Generated by Django 4.2.1 on 2023-05-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_user_dynamicpricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingentry',
            name='fpi',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='total_cars_inside',
            field=models.IntegerField(default=0),
        ),
    ]
