# Generated by Django 4.2.1 on 2023-05-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_parkingentry_user_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingentry',
            name='floor_last_seen',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
