# Generated by Django 4.2.1 on 2023-05-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_user_auth_token_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('floor_number', models.IntegerField()),
                ('cars_parked', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='parkingentry',
            name='floorassigned',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='user',
            name='floorcapacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
